server:
  port: ${PORT:8082}

spring:
  application:
    name: empleados-service
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/cafedb}
    username: ${DB_USER:cafeuser}
    password: ${DB_PASSWORD:cafepass}
  sql:
    init:
      mode: always
      platform: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,info
